src/Entity/Don.php
<?php

namespace App\Entity;
use Symfony\Component\Validator\Constraints as Assert;
use App\Repository\DonRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
#[ORM\Entity(repositoryClass: DonRepository::class)]
class Don
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[Groups("dons")]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    #[Assert\NotBlank(message:"il faut saisir id_ben")]
    #[Groups("dons")]
    #[Assert\Positive]
    private ?int $id_ben = null;

    #[ORM\Column(length: 20)]
    #[Assert\NotBlank(message:"il faut saisir titre")]
    #[Groups("dons")]
    private ?string $titre = null;

    #[ORM\Column]
    #[Assert\NotBlank(message:"il faut saisir Qte")]
    #[Groups("dons")]
    #[Assert\Positive]
    private ?int $qte = null;

    #[ORM\ManyToOne(inversedBy: 'dons')]
   
    private ?Categorie $id_cat = null;

    #[ORM\Column(length: 30)]
    #[Assert\NotBlank(message:"il faut saisir type_cat")]
    private ?string $type = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
   
    private ?\DateTimeInterface $date = null;

    #[ORM\Column]
    #[Assert\NotBlank(message:"il faut saisir choisir local")]
    #[Assert\Positive]
    private ?int $id_local = null;

    #[ORM\Column(length: 255)]
    
    
    private ?string $imge = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdBen(): ?int
    {
        return $this->id_ben;
    }

    public function setIdBen(int $id_ben): self
    {
        $this->id_ben = $id_ben;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(?string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getQte(): ?int
    {
        return $this->qte;
    }

    public function setQte(?int $qte): self
    {
        $this->qte = $qte;

        return $this;
    }

    public function getIdCat(): ?Categorie
    {
        return $this->id_cat;
    }

    public function setIdCat(?Categorie $id_cat): self
    {
        $this->id_cat = $id_cat;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getIdLocal(): ?int
    {
        return $this->id_local;
    }

    public function setIdLocal(?int $id_local): self
    {
        $this->id_local = $id_local;

        return $this;
    }

    public function getImge(): ?string
    {
        return $this->imge;
    }

    public function setImge(?string $imge): self
    {
        $this->imge = $imge;

        return $this;
    }
}

src/Form/DonType.php
<?php

namespace App\Form;

use App\Entity\Categorie;
use App\Entity\Don;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Validator\Constraints\File;

class DonType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('id_ben',NULL,array('attr' => array('class' => 'form-control','style' => 'margin-right:5px')))
            ->add('titre',NULL,array('attr' => array('class' => 'form-control','style' => 'margin-right:5px')))
            ->add('qte',NULL,array('attr' => array('class' => 'form-control','style' => 'margin-right:5px')))
            ->add('type',NULL,array('attr' => array('class' => 'form-control','style' => 'margin-right:5px')))
            ->add('date',NULL,array('attr' => array('class' => 'form-control','style' => 'margin-right:5px')))
            ->add('id_local',NULL,array('attr' => array('class' => 'form-control','style' => 'margin-right:5px')))
            //->add('id_cat',NULL,array('attr' => array('class' => 'form-control','style' => 'margin-right:5px')))
           
            ->add('imge', FileType::class, [
                'label' => 'votre image (PDF file)',

                // unmapped means that this field is not associated to any entity property
                'mapped' => false,

                // make it optional so you don't have to re-upload the PDF file
                // every time you edit the Product details
                'required' => false,

                // unmapped fields can't define their validation using annotations
                // in the associated entity, so you can use the PHP constraint classes
                'constraints' => [
                    new File([
                        'maxSize' => '1024k',
                        'mimeTypes' => [
                            'image/jpeg',
                            'image/png',
                            'image/gif',
                        ],
                        'mimeTypesMessage' => 'Please upload an image ',
                    ])
                ],
            ])
            ->add('save', SubmitType::class,);
            
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Don::class,
        ]);
    }
}

src/Controller/DonController.php
<?php

namespace App\Controller;

use App\Entity\Don;
use App\Form\DonType;
use App\Repository\DonRepository;
use App\Repository\CategorieRepository;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\Serializer\SerializerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
use Doctrine\ORM\EntityManagerInterface;

#[Route('/don')]
class DonController extends AbstractController
{
    


    #[Route('/', name: 'app_don_index')]
    public function index(DonRepository $donRepository,Request $request,SluggerInterface $slugger): Response
    {
        $don = new Don();
        $form = $this->createForm(donType::class, $don);
        $form->handleRequest($request);

if ($form->isSubmitted() && $form->isValid()) {
    $photo = $form->get('imge')->getData();

    // this condition is needed because the 'brochure' field is not required
    // so the PDF file must be processed only when a file is uploaded
    if ($photo) {
        $originalFilename = pathinfo($photo->getClientOriginalName(), PATHINFO_FILENAME);
        // this is needed to safely include the file name as part of the URL
        $safeFilename = $slugger->slug($originalFilename);
        $newFilename = $safeFilename.'-'.uniqid().'.'.$photo->guessExtension();

        // Move the file to the directory where brochures are stored
        try {
            $photo->move(
                $this->getParameter('don_directory'),
                $newFilename
            );
        } catch (FileException $e) {
            // ... handle exception if something happens during file upload
        }

        // updates the 'brochureFilename' property to store the PDF file name
        // instead of its contents
        $don->setImge($newFilename);
    }

            $donRepository->save($don, true);

            return $this->redirectToRoute('app_don_index');
        }






        return $this->render('don/index.html.twig', array('dons' => $donRepository->findAll(),'form' => $form->CreateView()));
    }

    #[Route('/statisreclamation', name: 'app_reclamation_statisreclamation', methods: ['GET'])]
public function statisreclamation(DonRepository $donRepository)
{
    //on va chercher les categories
    $rech = $donRepository->barDep();
    $arr = $donRepository->barArr();
    
    $bar = new barChart ();
    $bar->getData()->setArrayToDataTable(
        [['don', 'Type'],
         ['Collecte des déchets', intVal($rech)],
         ['Éclairage public', intVal($arr)],
        

        ]
    );

    $bar->getOptions()->setTitle('les Dons');
    $bar->getOptions()->getHAxis()->setTitle('Nombre de don');
    $bar->getOptions()->getHAxis()->setMinValue(0);
    $bar->getOptions()->getVAxis()->setTitle('Type');
    $bar->getOptions()->SetWidth(800);
    $bar->getOptions()->SetHeight(400);


    return $this->render('Don/statisDon.html.twig', array('bar'=> $bar )); 

}

    #[Route('/new', name: 'app_don_new', methods: ['GET', 'POST'])]
    public function new(Request $request, DonRepository $donRepository,SluggerInterface $slugger): Response
    {
        $don = new Don();
        $form = $this->createForm(DonType::class, $don);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $photo = $form->get('imge')->getData();

            // this condition is needed because the 'brochure' field is not required
            // so the PDF file must be processed only when a file is uploaded
            if ($photo) {
                $originalFilename = pathinfo($photo->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$photo->guessExtension();

                // Move the file to the directory where brochures are stored
                try {
                    $photo->move(
                        $this->getParameter('don_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }

                // updates the 'brochureFilename' property to store the PDF file name
                // instead of its contents
                $don->setImge($newFilename);
            }

            $donRepository->save($don, true);

            return $this->redirectToRoute('app_don_new', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('don/new.html.twig', [
            'don' => $don,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_don_show', methods: ['GET'])]
    public function show(Don $don): Response
    {
        return $this->render('don/show.html.twig', [
            'don' => $don,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_don_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Don $don, DonRepository $donRepository): Response
    {
        $form = $this->createForm(DonType::class, $don);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $donRepository->save($don, true);

            return $this->redirectToRoute('app_don_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('don/edit.html.twig', [
            'don' => $don,
            'form' => $form,
        ]);
    }

    #[Route('/remove/{id}', name: 'app_don_delete')]
    public function delete(Request $request, Don $don, DonRepository $donRepository): Response
    {
       
            $donRepository->remove($don, true);
        

        return $this->redirectToRoute('app_don_index');
    }

    /**
     * @Route("/statis", name="app_stattttt")
     */
    public function statsParType(EntityManagerInterface $entityManager): Response
    {
        // Récupération des statistiques des offres par type
        $stats = $entityManager->createQuery(
            'SELECT t.nom AS categorie, COUNT(o.id) AS nbdon
             FROM Don o
             JOIN o.Categorie t
             GROUP BY t.nom'
        )->getResult();

        // Retourne une vue Twig avec les statistiques des offres par type
        return $this->render('don/statistique.html.twig', [
            'stats' => $stats

        ]);
    }
    
////////////////////////json  pour mobile///////////////////////////////////////////////////


    #[Route('/affichage/mobile', name: 'app_don_allApp')]
    public function allApp(DonRepository $donRepository,SerializerInterface $s){
        $x=$donRepository->findAll();
    
        $json=$s->serialize($x,'json',['groups'=>"dons"]);
        return new Response($json);
     
    }
    #[Route('/ajout/mobile', name: 'app_don_ajoutApp')]
    public function AjoutMobil(Request $req,NormalizerInterface $s,ManagerRegistry $doctrine){
        
        $em = $doctrine->getManager();
        $don=new Don();
        $don->setIdBen($req->get('id_ben'));
        $don->setTitre($req->get('titre'));
        $don->setQte($req->get('qte'));
        $don->setType($req->get('type'));
        $don->setDate($req->get('date'));
        $don->setIdLocal($req->get('id_local'));
        $don->setImge($req->get('imge'));
        $em -> persist($don);
        $em->flush();
        $json=$s->normalize($don,'json',['groups'=>"dons"]);
        return new Response(json_encode($json));
     
    }

    #[Route('/Update/mobile/{id}', name: 'app_don_editApp')]
    public function UpdateMobile(Request $req,$id,NormalizerInterface $s,ManagerRegistry $doctrine){
        
        $em = $doctrine->getManager();
        $don=$em->getRepository(Don::class)->find($id);
        $don->setIdBen($req->get('id_ben'));
        $don->setTitre($req->get('titre'));
        $don->setQte($req->get('qte'));
        $don->setType($req->get('type'));
        $don->setDate($req->get('date'));
        $don->setIdLocal($req->get('id_local'));
        $don->setImge($req->get('imge'));
        $em->flush();
        $json=$s->normalize($don,'json',['groups'=>"dons"]);
        return new Response(" don updated successfully".json_encode($json));
     
    }


    #[Route('/delete/mobile/{id}', name: 'app__deleteApp')]
    public function deleteMobile($id,NormalizerInterface $s,ManagerRegistry $doctrine)
    {
        
        $em = $doctrine->getManager();
        $don=$em->getRepository(Don::class)->find($id);
        $em->remove($don);
        
        
        $em->flush();

        $json=$s->normalize($don,'json',['groups'=>"dons"]);
        return new Response(" don deleted successfully".json_encode($json));
     
    }
}

templates/don/_delete_form.html.twig
<form method="post" action="{{ path('app_don_delete', {'id': don.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ don.id) }}">
    <button class="btn">Delete</button>
</form>

templates/don/_form.html.twig
{{ form_start(form, {'attr': {novalidate: 'novalidate'}})  }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/don/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Don{% endblock %}

{% block body %}
<!-- ======= Header ======= -->
  <header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
      <a href="index.html" class="logo d-flex align-items-center">
       
        <span class="d-none d-lg-block">Sa7etna</span>
      </a>
      <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

    <div class="search-bar">
      <form class="search-form d-flex align-items-center" method="POST" action="">
        <input type="text" name="query" placeholder="Recherche" title="Enter search keyword">
        <button type="submit" title="Recherche"><i class="bi bi-search"></i></button>
      </form>
    </div><!-- End Search Bar -->

    <nav class="header-nav ms-auto">
      <ul class="d-flex align-items-center">

        <li class="nav-item d-block d-lg-none">
          <a class="nav-link nav-icon search-bar-toggle " href="">
            <i class="bi bi-search"></i>
          </a>
        </li><!-- End Search Icon-->

        <li class="nav-item dropdown">

          <!-- End Notification Icon -->

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow notifications">
            <li class="dropdown-header">
              You have 4 new notifications
              <a href=""><span class="badge rounded-pill bg-primary p-2 ms-2">View all</span></a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li class="notification-item">
              <i class="bi bi-exclamation-circle text-warning"></i>
              <div>
                <h4>Lorem Ipsum</h4>
                <p>Quae dolorem earum veritatis oditseno</p>
                <p>30 min. ago</p>
              </div>
            </li>

            <li>
              <hr class="dropdown-divider">
            </li>

            <li class="notification-item">
              <i class="bi bi-x-circle text-danger"></i>
              <div>
                <h4>Atque rerum nesciunt</h4>
                <p>Quae dolorem earum veritatis oditseno</p>
                <p>1 hr. ago</p>
              </div>
            </li>

            <li>
              <hr class="dropdown-divider">
            </li>

            <li class="notification-item">
              <i class="bi bi-check-circle text-success"></i>
              <div>
                <h4>Sit rerum fuga</h4>
                <p>Quae dolorem earum veritatis oditseno</p>
                <p>2 hrs. ago</p>
              </div>
            </li>

            <li>
              <hr class="dropdown-divider">
            </li>

            <li class="notification-item">
              <i class="bi bi-info-circle text-primary"></i>
              <div>
                <h4>Dicta reprehenderit</h4>
                <p>Quae dolorem earum veritatis oditseno</p>
                <p>4 hrs. ago</p>
              </div>
            </li>

            <li>
              <hr class="dropdown-divider">
            </li>
            <li class="dropdown-footer">
              <a href="">Show all notifications</a>
            </li>

          </ul><!-- End Notification Dropdown Items -->

        </li><!-- End Notification Nav -->

        <li class="nav-item dropdown">

          <a class="nav-link nav-icon" href="" data-bs-toggle="dropdown">
            <i class="bi bi-chat-left-text"></i>
            <span class="badge bg-success badge-number">3</span>
          </a><!-- End Messages Icon -->

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow messages">
            <li class="dropdown-header">
              You have 3 new messages
              <a href=""><span class="badge rounded-pill bg-primary p-2 ms-2">View all</span></a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li class="message-item">
              <a href="">
                <img src="assets/img/messages-1.jpg" alt="" class="rounded-circle">
                <div>
                  <h4>Maria Hudson</h4>
                  <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>
                  <p>4 hrs. ago</p>
                </div>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li class="message-item">
              <a href="">
                <img src="assets/img/messages-2.jpg" alt="" class="rounded-circle">
                <div>
                  <h4>Anna Nelson</h4>
                  <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>
                  <p>6 hrs. ago</p>
                </div>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li class="message-item">
              <a href="">
                <img src="assets/img/messages-3.jpg" alt="" class="rounded-circle">
                <div>
                  <h4>David Muldon</h4>
                  <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>
                  <p>8 hrs. ago</p>
                </div>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li class="dropdown-footer">
              <a href="">Show all messages</a>
            </li>

          </ul><!-- End Messages Dropdown Items -->

        </li><!-- End Messages Nav -->

        <li class="nav-item dropdown pe-3">

          <a class="nav-link nav-profile d-flex align-items-center pe-0" href="" data-bs-toggle="dropdown">
            <img src="assets/img/profile-img.jpg" alt="Profile" class="rounded-circle">
            <span class="d-none d-md-block dropdown-toggle ps-2">D.Mahdi</span>
          </a><!-- End Profile Iamge Icon -->

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
            <li class="dropdown-header">
              <h6>Mahdi Dahmani</h6>
              <span>Web Designer</span>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="users-profile.html">
                <i class="bi bi-person"></i>
                <span>My Profile</span>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="users-profile.html">
                <i class="bi bi-gear"></i>
                <span>Account Settings</span>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="pages-faq.html">
                <i class="bi bi-question-circle"></i>
                <span>Need Help?</span>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="">
                <i class="bi bi-box-arrow-right"></i>
                <span>Sign Out</span>
              </a>
            </li>

          </ul><!-- End Profile Dropdown Items -->
        </li><!-- End Profile Nav -->

      </ul>
    </nav><!-- End Icons Navigation -->

  </header><!-- End Header -->
  <aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

      <li class="nav-item">
        <a class="nav-link " href="index.html">
          <i class="bi bi-grid"></i>
          <span>Dashboard</span>
        </a>
      
        <a class="nav-link " href="index.html">
          <i class="bi bi-person"></i>
          <span>Gestion User</span>
        </a>
      
        <a class="nav-link " href="index.html">
          <i class="bi bi-grid"></i>
          <span>Gestion Locaux</span>
        </a>
        <a class="nav-link " href="index.html">
          <i class="bi bi-grid"></i>
          <span>Gestion Medicaments</span>
        </a>
        <a class="nav-link " href="/don/">
          <i class="bi bi-grid"></i>
          <span>Gestion  Dons</span>
        </a>
        <a class="nav-link " href="/categorie/">
          <i class="bi bi-grid"></i>
          <span>Gestion  categorie</span>
        </a>
        <a class="nav-link " href="index.html">
          <i class="bi bi-grid"></i>
          <span>Gestion Reclamations</span>
        </a>
        <a class="nav-link " href="index.html">
          <i class="bi bi-grid"></i>
          <span>Gestion Articles</span>
        </a>

      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="charts-nav" data-bs-toggle="collapse" >
          <i class="bi bi-bar-chart"></i><span>Charts</span><i class="bi bi-chevron-down ms-auto"></i>
        </a>
        <ul id="charts-nav" class="nav-content collapse " data-bs-parent="sidebar-nav">
          <li>
            <a ">
              <i class="bi bi-circle"></i><span>Chart.js</span>
            </a>
          </li>
          <li>
            <a >
              <i class="bi bi-circle"></i><span>ApexCharts</span>
            </a>
          </li>
          <li>
            <a >
              <i class="bi bi-circle"></i><span>ECharts</span>
            </a>
          </li>
        </ul>
      </li>

      

      <li class="nav-heading">Pages</li>

      <li class="nav-item">
        <a class="nav-link collapsed" href="users-profile.html">
          <i class="bi bi-person"></i>
          <span>Profile</span>
        </a>
      </li>

     
      <li class="nav-item">
        <a class="nav-link collapsed" href="pages-contact.html">
          <i class="bi bi-envelope"></i>
          <span>Contact</span>
        </a>
      </li>

      

      <li class="nav-item">
        <a class="nav-link collapsed" href="pages-login.html">
          <i class="bi bi-box-arrow-in-right"></i>
          <span>Login</span>
        </a>
      </li>

     

      

    </ul>

  </aside>
  <main id="main" class="main">

    <div class="pagetitle">
      <h1>Dashboard</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="index.html">Acceuil</a></li>
          <li class="breadcrumb-item active">Dashboard</li>
        </ol>
      </nav>
    <h1>Edit Don</h1>

    {{ include('don/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_don_index') }}">back to list</a>

    {{ include('don/_delete_form.html.twig') }}
    </main>
    <footer id="footer" class="footer">
    <div class="copyright"> 
      &copy; Copyright <strong><span>Sa7etna</span></strong>. Tous les droits reservé.
    </div>
    <div class="credits">
     
    </div>
  </footer>

  <a href="" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

{% endblock %}

templates/don/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Don{% endblock %}

{% block body %}
    <h1>Don</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ don.id }}</td>
            </tr>
            <tr>
                <th>Id_ben</th>
                <td>{{ don.idBen }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ don.titre }}</td>
            </tr>
            <tr>
                <th>Qte</th>
                <td>{{ don.qte }}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{ don.type }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ don.date ? don.date|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Id_local</th>
                <td>{{ don.idLocal }}</td>
            </tr>
            <tr>
                <th>Imge</th>
                 <td><img src="{{asset ('uploads/donimage/' ~ don.imge)}}"   height="300px"></td>
              
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_don_index') }}">back to list</a>

    <a href="{{ path('app_don_edit', {'id': don.id}) }}">edit</a>
    

    {{ include('don/_delete_form.html.twig') }}
{% endblock %}

templates/don/statistique.html.twig
{% extends 'base-back.html.twig' %}

{% block title %}Statistiques des dons par categorie{% endblock %}

{% block body %}
    <h1>Statistiques des dons par categorie</h1>

    <canvas id="myChart"></canvas>

    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script>
        var ctx = document.getElementById('myChart').getContext('2d');
        var data = {
            labels: [
                {% for stat in stats %}
                    "{{ stat['categorie'] }}",
                {% endfor %}
            ],
            datasets: [{
                label: 'Nombre d\'dons',
                data: [
                    {% for stat in stats %}
                        {{ stat['nbdons'] }},
                    {% endfor %}
                ],
                backgroundColor: 'rgba(255, 99, 132, 0.2)',
                borderColor: 'rgba(255, 99, 132, 1)',
                borderWidth: 1
            }]
        };
        var myChart = new Chart(ctx, {
            type: 'line',
            data: data,
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                        }
                    }]
                }
            }
        });
    </script>
{% endblock %}